name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get install -y libpq-dev

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run RSpec tests
        run: |
           bundle exec rspec spec/models spec/requests
          

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
